name: audio_player_example
description: Demonstrates how to use the audio_player plugin.
version: 1.0.10
publish_to: 'none'

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  audio_player:
    path: ../
flutter:
  uses-material-design: true
  assets:
    - assets/


